### ISSUE TITLE
用这个工具按需引入后如何定义自定义主题呢

### ISSUE THREAD

**Issue by hi-wendy** [element-plus/vite-plugin-element-plus#15]
你好，用这个工具按需引入后如何定义自定义主题呢？不太会玩

**Comment by YunYouJun** [comment]
按需引入后，参考选项使用 source 引入，即 `.scss`，然后修改变量定制主题。

或者直接修改 css var。

```css
:root {
  --el-color-primary: red;
}
```
